### PR TITLE
Change Boolean false state

### PR DESCRIPTION
**Pull request by ixje**
Closes https://github.com/neo-project/neo-vm/issues/129
a Boolean StackItem in either `false` or `true` state should always return at least 1 byte for `GetByteArray()`. This is the default behaviour in C#'s build in [BitConverter](https://docs.microsoft.com/en-us/dotnet/api/system.bitconverter) as well as many other languages. It is misleading for it to return an empty array as that will lead to a length/size of 0, whereas the item still takes up memory space.

### CODE REVIEW

**Comment by erikzhang** [comment]
Will this change break old contracts?

**Comment by ixje** [comment]
As far as I can tell not. 
1) all VM tests still pass. I only adjusted the return size from `0` to `1` in the PR
2) the original author of `neo-python` ported the `Boolean` stackitem code wrong. Meaning it has been returning 1 byte for a `false` state (as now being proposed in the PR) since the code was first written back in 2017. I just discovered this after a failed JSON test, but I've seen no reports for `neo-python` indicating deviating contract execution results because of this.

What will behave differently in some cases is
https://github.com/neo-project/neo-vm/blob/a3f94445ff8de4fdea9388652f5dff9243d2c13b/src/neo-vm/Types/Boolean.cs#L32

so e.g. a `BigInteger.zero` would now equal a `Boolean false`, which is more accurate than before. I don't see a straight forward way for test all existing contracts if such scenario's are in use and ifso if they break something.

**Comment by erikzhang** [comment]
It needs to be tested.

**Comment by ixje** [comment]
Ok, we don't trust the existing tests due to lack of coverage. I can understand that. 

Do you have a suggestion on how you would like to see it tested? I can sync the whole chain from scratch with this change and do contract storage comparisons, but that might not suit your needs therefore I'm asking for directions/input/ideas..

**Comment by erikzhang** [comment]
I think it's okay if it doesn't break old contracts.

**Comment by vncoelho** [comment]
We have currently created this procedure here, it compares two neo-cli versions and checks storage differences: https://github.com/NeoResearch/neo-tests/tree/master/clients-assert-testnet

**Comment by vncoelho** [comment]
We are currently thinking about how to integrate this here, we are afraid this is to much costly for a UT.

**Comment by ixje** [comment]
thanks for the tip @vncoelho . What is the benefit of using your docker setup vs manually compiling a client with this fix , syncing using the offline chain files and comparing the storage with the normal client?

**Comment by vncoelho** [comment]
I mean, in that script we already start a plugin that export all storage differences (in NEO 3.0 we gonna have MPT and this will not be necessary).

However, nowadays, that sounds necessary.
That docker-compose keep the healthy status of the containers by checking if their storage are the same.
If we have difference in storage that will result in unhealthy state and we will know that the difference has a backward effect on old contracts.

**Comment by vncoelho** [comment]
We could also manually export storage and check this against  https://github.com/NeoResearch/neo-storage-audit

**Comment by shargon** [comment]
This could break old contracts.

**Comment by igormcoelho** [comment]
Perhaps we do this @ixje . What are the scenarios generated from neo-boa and neon compiler, involving Boolean state? Can you try some and we think about them?
If the all existing compilers generate a compatible code (which is possible) and no deviations happen on global storage, it's safe to assume this new path on Neo 2.

**Comment by igormcoelho** [comment]
Anyway, it makes more sense to focus on Neo 3, so we don't break anything, and develop things faster.

**Comment by ixje** [comment]
> This could break old contracts. Good for neo 3, not for neo 2

Do you have an example or is this a guess?

NEO 3.0 should be backwards compatible, no? So we have to figure out the effect anyway.

**Comment by igormcoelho** [comment]
We will need to redeploy many contracts on Neo 3 due to global assets abolished... so bavkwards compatibility can be flexible in this case.

**Comment by shargon** [comment]
@ixje can you make the same as this but for master (neo 3.x) and close this pull request?

**Comment by ixje** [comment]
@shargon fixed. Changed destination to `master` branch and force pushed a "clean commit".

**Comment by shargon** [comment]
@erikzhang are you agree with merge it? in the future we can check if is valid for neo2, but i think that is not needed in neo2, and should be only for neo3

**Pull request merged**
