### PR TITLE
More unit tests

### PR DESCRIPTION
**Pull request by shargon**
Added:

- `PUSHBYTES2` to `PUSHBYTES74`
- `SYSCALL`
- `ARRAYSIZE`
- `LEFT`
- `RIGHT`

### CODE REVIEW

**Comment by erikzhang** [comment]
When you are ready, please merge it by yourself.

**Comment by shargon** [comment]
@erikzhang `RIGHT` set the state to `Fault` if exceed the string length, but `LEFT` don't, is this correct?

**Comment by erikzhang** [comment]
> `RIGHT` set the state to `Fault` if exceed the string length, but `LEFT` don't, is this correct?

Yes.

**Comment by shargon** [comment]
We can merge this now, and i will make more in other PR.

**Pull request merged**
