### PR TITLE
Expand documentation of NEWARRAY and NEWSTRUCT opcodes

### PR DESCRIPTION
**Pull request by fyrchik**
PR #91 implemented ability to convert from Array to Struct and vice
versa.
https://github.com/neo-project/neo-vm/pull/91

This PR adds proper doc comments.

### CODE REVIEW

**Comment by roman-khimov** [comment]
I think you should also mention here the thing that was discussed in nspcc-dev/neo-go#360 --- after #91 `NEWARRAY` on array and `NEWSTRUCT` on struct are essentially noops.

**Comment by devhawk** [comment]
@shargon we should make sure https://github.com/neo-ngd/NEO3-Development-Guide is up to date with correct docs. Can you either file an issue or make sure those docs are up to date w/ latest source changes?

**Comment by shargon** [comment]
@devhawk NEWARRAY and NEWSTRUCT must be updated in https://github.com/neo-ngd/NEO3-Development-Guide/tree/master/en/NeoVM#newarray because now in order to convert between types, can receive an Array and a struct.

**Comment by devhawk** [comment]
You can file bugs on that repo: https://github.com/neo-ngd/NEO3-Development-Guide/issues

**Pull request merged**
