### PR TITLE
Remove BOM from *.json test files

### PR DESCRIPTION
**Pull request by fyrchik**
Some of the json tests have BOM marker at the beginning of the file (as was also noted in the first comment #94 ). I see no value in it and it has created some difficulties when trying to parse them in `Go`.

### CODE REVIEW

**Comment by shargon** [comment]
We should wait for https://github.com/neo-project/neo/pull/1083 before merge this

**Comment by erikzhang** [comment]
Why #198 passes without these changes?

**Comment by shargon** [comment]
I think that these changes are repeated, because for example `APPEND.json` has the same changes in both PR

**Comment by erikzhang** [comment]
Then I will rebase it to #198 and see if this is the case.

**Comment by erikzhang** [comment]
No luck.

**Comment by shargon** [comment]
The file is the same, but still there 🤔

**Comment by shargon** [comment]
I checked `APPEND.json` and is exactly the same in both branches

`0071C77CE46E4EB47F3C328731B76A190FBADE373718385FF835AF466AE110EB`

**Comment by shargon** [comment]
I think that travis is checking these files now, but i don't know why appears as changed if is the same as my pull request.
@lock9 any idea?

**Comment by lock9** [comment]
I think this is not needed

**Pull request closed without merging**
