### PR TITLE
More or equal on JUMP

### PR DESCRIPTION
**Pull request by shargon**
This check should not be "more or equal"?

### CODE REVIEW

**Comment by erikzhang** [comment]
If `InstructionPointer` is at the end of the script, it will be an default `OpCode.RET`.
https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/ExecutionEngine.cs#L961

**Comment by shargon** [comment]
Then it is intentional to jump to `RET` ?

**Comment by erikzhang** [comment]
>Then it is intentional to jump to `RET`?

Yes. Or should we avoid that?

**Comment by localhuman** [comment]
Can we assume that the last instruction will always be a `RET` opcode?

**Comment by erikzhang** [comment]
> Can we assume that the last instruction will always be a RET opcode?

Yes.

**Comment by shargon** [comment]
Then i close this, if you consider it necessary, you can reopen it!

**Pull request closed without merging**
