### PR TITLE
Fix for NULL checks

### PR DESCRIPTION
**Pull request by shargon**
Partial fix for https://github.com/neo-project/neo-devpack-dotnet/issues/114

### CODE REVIEW

**Comment by erikzhang** [comment]
`NUMEQUAL` is for numbers. Maybe `ceq` should be converted to `EQUAL`. @lightszero Can you confirm it?

**Comment by lightszero** [comment]
ceq in IL means numequal

reference to object is be looks as a number，like NULL
so we need convert LDNULL ceq to NEOVM ISNULL

I will work on it.

**Comment by erikzhang** [comment]
```c#
value == null
```

```c#
null == value
```

Do they generate the same IL?

**Comment by lightszero** [comment]
> ```cs
> value == null
> ```
> 
> ```cs
> null == value
> ```
> 
> Do they generate the same IL?

yes

and

value is null
is the same IL

**Comment by shargon** [comment]
Good to know! i close it

**Pull request closed without merging**
