### PR TITLE
Add OnExecutionStart

### PR DESCRIPTION
**Pull request by devhawk**
For time travel debugging, the trace capture ApplicationEngine needs to capture engine state at start of execution. This can be done in PreExecuteInstruction, but requires tracking state to ensure this initial trace is only captured once. Having an overridable OnExecutionStart method called at the start of execution would simplify this logic.

### CODE REVIEW

**Comment by erikzhang** [comment]
The `ExecutionEngine` can be started without calling `Execute()`.

For example:

```c#
Debugger debugger = new Debugger(engine);
debugger.Execute();
```

**Comment by shargon** [comment]
I prefer to change `Execute` to `virtual`

**Comment by devhawk** [comment]
> The `ExecutionEngine` can be started without calling `Execute()`.
> 
> For example:
> 
> ```cs
> Debugger debugger = new Debugger(engine);
> debugger.Execute();
> ```

This won't work for Time Travel Debugging trace capture. TTD uses the new IApplicationEnginerProvider feature to substitute an ApplicationEngine subclass that captures the TTD traces. I need a mechanism to capture the starting state from the ApplicationEngine subclass.

**Comment by devhawk** [comment]
> I prefer to change `Execute` to `virtual`

This works for me if it works for @erikzhang

**Comment by devhawk** [comment]
> > I prefer to change `Execute` to `virtual`
> 
> This works for me if it works for @erikzhang

Actually, I like this better - easy to insert trace capture at start and end of execution this way.

**Pull request closed without merging**
