### PR TITLE
Check items after copy an array/struct (3x)

### PR DESCRIPTION
**Pull request by shargon**
Acording to the conversation on: https://github.com/neo-project/neo/pull/1100/files with @vang1ong7ang

### CODE REVIEW

**Comment by erikzhang** [comment]
@shargon Do you think we should skip checking the stack when FAULT? #206

**Comment by shargon** [comment]
> Do you think we should skip checking the stack when FAULT? #206

I think that all the VM should have the same behaviour, and this check can ensure that this happend.

**Comment by erikzhang** [comment]
Conflict

**Comment by shargon** [comment]
Solved

**Pull request merged**
