### PR TITLE
IInteropService

### PR DESCRIPTION
**Pull request by shargon**
Allow to use any class as InteropService

### CODE REVIEW

**Comment by erikzhang** [comment]
Why not inherit from `InteropService`? Just like:
https://github.com/neo-project/neo/blob/40f76d24b5d529d267bcad535a100b4376027703/neo/SmartContract/StandardService.cs#L19

**Comment by shargon** [comment]
Because we don't have control of when `Invoke` is called, so we can't redirect to our generic class, only is possible to `Register`, and this task is done outside in other class

**Comment by shargon** [comment]
In neo-sharp we have our `InteropService` https://github.com/CityOfZion/neo-sharp/blob/2e62c668cdfe5388236e8ed79cfcea53586d9e3d/src/NeoSharp.VM/Types/InteropService.cs

This class want to unify all syscall, regardless of which virtual machine is used. So we need to be able to intercep the invoke in our class.

Our goal is allow nep-sharp to use official NeoVM, and HyperVM (c++) maybe others in the future. Same logic, different implementations.

**Comment by shargon** [comment]
Closed on https://github.com/neo-project/neo-vm/pull/67

**Pull request closed without merging**
