### PR TITLE
Jump table draft

### PR DESCRIPTION
**Pull request by shargon**
**Is a draft, not all opcodes was moved**

This could allow us to change the behaviour of certains opcodes according to the height, we can improve the VM in the future without taking care about breaking changes.

this close https://github.com/neo-project/neo-vm/issues/142

### CODE REVIEW

**Comment by erikzhang** [comment]
We are looking for ways to decouple NeoVM from the blockchain, and then you add something based on **height**. . .

**Comment by shargon** [comment]
how?

**Comment by erikzhang** [comment]
Can we add this when we need breaking changes?

**Comment by shargon** [comment]
Of course, is only and idea. We can deep into it more, and in the future take the best solution.

**Comment by lock9** [comment]
Maybe this should be added to neo? Do we need the VM to be an interface?

**Comment by shargon** [comment]
Closed but the issue https://github.com/neo-project/neo-vm/issues/142 will remain

**Pull request closed without merging**
