### PR TITLE
DebuggerDisplay

### PR DESCRIPTION
**Pull request by shargon**
`DebuggerDisplay` Is very useful when debug smart contracts in virtual machine

### CODE REVIEW

**Comment by erikzhang** [comment]
Most of the changes are about the style.

**Comment by shargon** [comment]
Do you prefer splitted in multiple PR?

**Comment by erikzhang** [comment]
I think a PR should only do a set of related functions. Also, I prefer to apply this style only to properties.

**Comment by shargon** [comment]
Done!

**Comment by shargon** [comment]
Good improvement! I thought that it only worked with field or properties!

**Pull request merged**
