### PR TITLE
Add OnStateChanged()

### PR DESCRIPTION
**Pull request by erikzhang**
Close #319, close #320

### CODE REVIEW

**Comment by erikzhang** [comment]
`PreExecuteInstruction()` + `PostExecuteInstruction()` + `OnStateChanged()` can replace the `Trace()`. What do you think? @devhawk

**Comment by devhawk** [comment]
Tracing needs the ability (only when enabled, of course) to capture enough of the state of the execution engine (not just VMState - InvocationStack and Storage are also needed) for every instruction during normal contract execution (i.e. in Blockchain.Persist). This PR would only trigger OnStateChange when VMState changed.

**Comment by devhawk** [comment]
I think this approach is more complex than the Trace approach, but it's workable. It means having to spread trace logic across at least two locations: ApplicationEngine will need trace code in at least PreExecuteInstruction and OnStateChange (maybe PostExecuteInstruction as well, I need to review the VM code to know for sure). 

Given the low performance impact of the Trace function, I'm don't think the complexity increase of this approach is worth it. As I said in the Trace PR, for scenarios when there is no trace enabled, the Trace method is just a virtual method dispatch plus a null check. Looking at the [native codegen from SharpLab.io](https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQ71wMwAJG4DCuA3urhbgA4BOAlgG5jACmuNLYAJgPYB2AGwCeuHgCMAViwDGwUZNwBeXHwCuAgQG5MaSvjwM6NYKrADcYnj3MAFHhGAAKAJSlyeynADsuYDVUs2rqUAL7uFOH6uIbGpuZwACy4APJ8ACo0YNIsLqS4kXoA9IW4WSZmvpnZuAI8AOZ00rh1PCwQuAAWLByRYcER/VEx5fFJGVk5rmSDenQAZriO4hK4AITKahpTBR4UqePZLkG7FH16Z5SROPhJALK50yfRYDS4AF5KuHYORzsUB5Njic4EgAJyON7OIGndAhIA=), we're looking at execution 6 instructions in the Trace function when tracing is disabled. Pretty sure branch prediction logic will learn very quickly that the `jz` operation below will always succeed or fail for a given contract execution.

``` asm
ExecutionEngine.Trace()
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: cmp dword [ecx+0x4], 0x0
    L0007: jz L0011 
    L0009: mov eax, [ecx]
    L000b: mov eax, [eax+0x28]
    L000e: call dword [eax+0x14]
    L0011: pop ebp
    L0012: ret
```
That's not much worse than the default PostExecuteInstruction method, which is also a virtual method dispatch plus 2 instructions, executes on every instruction but isn't used in neo-core.

Performance and complexity issues aside, I can make this OnStateChanged approach work if need be. Note, it will also need to be backported to master-2.x.

**Comment by devhawk** [comment]
@erikzhang what about master-2.x support?

**Comment by erikzhang** [comment]
Is it necessary?

**Comment by devhawk** [comment]
If we want time travel / trace debugging support on Neo 2.x, then we need to port this back to master-2.x

**Pull request merged**
