### PR TITLE
FIX `SQRT`

### PR DESCRIPTION
**Pull request by vang1ong7ang**
#421 Related

### CODE REVIEW

**Comment by vang1ong7ang** [comment]
@superboyiii @ProDog  please help to test this PR to ensure the correctness.

**Comment by ProDog** [comment]
It's cheaper, but 4's sqrt is not right👀.
```
neo> invoke 0x01a8623d4d7afac0472f629d5a7c521e00e3149d sqrt [{"type":"Integer","value":"4"}]
Invoking script with: 'FBHAHwwEc3FydAwUnRTjAB5SfFqdYi9HwPp6TT1iqAFBYn1bUg=='
VM State: HALT
Gas Consumed: 0.0105069
Result Stack: [{"type":"Integer","value":"4"}]
Network fee: 0.0118058
Total fee: 0.0223127 GAS
Relay tx? (no|yes):
```

**Comment by vang1ong7ang** [comment]
@ProDog coooool you got it.

already fixed

**Comment by shargon** [comment]
@vang1ong7ang could you give me edit rights?

**Comment by vang1ong7ang** [comment]
@shargon Sure, and i have added it to you

**Review by ProDog — APPROVED** [review]
TESTED OK.

**Comment by shargon** [comment]
> @shargon Sure, and i have added it to you

I can't...

**Comment by vang1ong7ang** [comment]
@shargon check <https://github.com/neo-ngd/neo-vm/invitations> see if it works, if not, feel free to create new PR and close this one or edit the branch of this PR.

**Review by ProDog — DISMISSED** [review]

**Comment by shargon** [comment]
@vang1ong7ang there are no invitations, please check the PR

**Comment by vang1ong7ang** [comment]
@shargon sorry i invited `shagon` instead of `shargon` before :face_with_thermometer: . now it should work

**Review by shargon — APPROVED** [review]

**Comment by superboyiii** [comment]
@erikzhang Merge?

**Pull request merged**
