### PR TITLE
Better ReferenceCounter

### PR DESCRIPTION
**Pull request by erikzhang**
Use [Tarjan's strongly connected components algorithm](https://en.wikipedia.org/wiki/Tarjan's_strongly_connected_components_algorithm).

### CODE REVIEW

**Comment by erikzhang** [comment]
Can anyone test it to see if there is a performance improvement?

**Comment by shargon** [comment]
> Can anyone test it to see if there is a performance improvement?

I will, but I will need some days

**Comment by dusmart** [comment]
The optimization from #459 or #460 will also preventing us from DoS attacks such as https://github.com/neo-project/neo/issues/2725 as they cause lots of GC iterations.

**Comment by erikzhang** [comment]
#463 is the best. Closed this one.

**Pull request closed without merging**
