### PR TITLE
Revert "Fixes GetEntryScriptHash and GetCallingScriptHash (2.x) (#138)"

### PR DESCRIPTION
**Pull request by erikzhang**
This reverts commit 38c5dc0c63c70703f9d49970c2401e565972c3af.

### CODE REVIEW

**Comment by ixje** [comment]
Can you describe why this is needed? 
I had this ported to neo-python so need to know if I need to rollback as well.

**Comment by erikzhang** [comment]
#138 may not be compatible with previous contracts and is being tested.

**Comment by ixje** [comment]
Ok, I'll keep watching this issue then

**Comment by ixje** [comment]
😞

**Comment by vncoelho** [comment]
What happened, @ixje?

I am not sure if it really affected storage of Mainnet since I only compared for Testnet.
Did NGD confirmed inconsistencies, @erikzhang?
If true, let's keep 2.x like it is now and focus on the future.

**Comment by erikzhang** [comment]
I have not tested it myself, but the NGD team has confirmed this problem.

**Comment by superboyiii** [comment]
@vncoelho  Could be seen here for the [detail](https://github.com/neo-project/neo/issues/732)

**Comment by ixje** [comment]
@superboyiii there seems to be some doubt in whether this is the solution
> Should be, I think. Or if there might be a better solution...

Did you try a comparison with a version that had this PR merged to validate this _is_ the actual solution to the problem?

**Comment by superboyiii** [comment]
Yes, I just completed the test of revert#138, it got the same correct storage with v2.10.0 and v2.9.4. There actually has contradiction between storage compatibility and TAIL CALL fixing. What a pity.....

**Comment by ixje** [comment]
Great! Thanks for the input. Now I can confidently revert this change as well

**Pull request merged**
