### PR TITLE
NeoVM Runtime Versioning

### LINKED ISSUE #142: Versioning in VM
We should be able to change the behaviour of certains opcodes acording to the height of the block, because this VM is generic, acording to a set or interface provided in the constructor of `ExecutionEngine`.

This could be made with a `jump table`, like other blockchains does, because we can change the table acording to this parameter.

### PR DESCRIPTION
**Pull request by erikzhang**
Close #142

### CODE REVIEW

**Comment by erikzhang** [comment]
```c#
if (RuntimeVersion == xxx)
{
}
else
{
}
```

Doesn't it work?

**Comment by shargon** [comment]
It will work, but you are adding an extra comparation for each opcode instead of configure the environment  and use it. It will be slower.

**Comment by erikzhang** [comment]
Then we need to create a `Runtime` class and move the entire runtime environment into it. I don't think it's necessary to do this right now.

**Comment by shargon** [comment]
We can start with this, but in my mind I was thinking in something like this
```csharp
 protected ExecutionEngine(ReferenceCounter referenceCounter, ExecutionEngineLimits limits, RuntimeVersion version = RuntimeVersion.Latest)
        {
              if (RuntimeVersion == Latest)
              {
ExecuteInstruction = LastestExecuteInstruction;
              }
              else
              {
ExecuteInstruction = PreviousExecuteInstruction;
              }
}
```

**Review by shargon — APPROVED** [review]

**Review by shargon — APPROVED** [review]

**Comment by erikzhang** [comment]
Changes to the instruction set also need to be considered. In this way, the verification of `Script` is different. Needs to be reconsidered.

**Pull request closed without merging**
