### PR TITLE
Badge in readme

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by shargon** [comment]
I don't know what link for href...

**Comment by vncoelho** [comment]
I did not understand...aehuahea

**Comment by shargon** [comment]
If you click, you will navigate to badge web

**Comment by vncoelho** [comment]
It is directing to this link: https://camo.githubusercontent.com/3f2d9736c6b747b912ae80047154e8d559b1256d/68747470733a2f2f62616467652e667572792e696f2f67682f6e656f2d70726f6a6563742532466e656f2d766d2e737667

Is it bad? not trustable, right?

**Comment by shargon** [comment]
without sense

**Comment by vncoelho** [comment]
I do not know, where did you get this link? aehuaheauea

**Comment by vncoelho** [comment]
@shargon, check this example for the angular js:

`[npm version](https://www.npmjs.com/@angular/core)`

https://raw.githubusercontent.com/angular/angular/master/README.md

**Comment by vncoelho** [comment]
`[neo-vm version](https://github.com/neo-project/neo-vm/releases)`

**Comment by vncoelho** [comment]
Shargon, lets add number of lines as well and merge.

**Pull request merged**
