### PR TITLE
Allow null for relational operators

### PR DESCRIPTION
**Pull request by erikzhang**
Fix neo-project/neo-devpack-dotnet#527

### CODE REVIEW

**Comment by erikzhang** [comment]
@cloud8little It should fix neo-project/neo-devpack-dotnet#527. Please test.

**Comment by cloud8little** [comment]
@erikzhang  can it be done in the compiler? since the raw C# code should return a Boolean type.

**Comment by erikzhang** [comment]
We need to support nullable in VM.

**Review by shargon — DISMISSED** [review]

**Comment by ixje** [comment]
Can you provide a realistic test script that creates this situation? I'm unsure how this situation would arise and if this affects other implementations. Thanks!

**Comment by shargon** [comment]
I will add some tests

**Comment by erikzhang** [comment]
Merge?

**Review by shargon — APPROVED** [review]

**Pull request merged**
