### PR TITLE
Improve JSON ut

### PR DESCRIPTION
**Pull request by shargon**
According to https://github.com/neo-project/neo-vm/issues/244#issuecomment-562231764
Idea's owner: @roman-khimov

The problem with allow numbers is that we don't know which kind of numbers should be, bytes, integers, longs...

If we check the `OperandSize` we can know it, but I don't know if it will be a litlle confuse.

It is compatible with previous and new format.

### CODE REVIEW

**Comment by erikzhang** [comment]
If we are going to update all the json files, we'd better do it as soon as possible.

**Comment by roman-khimov** [comment]
Looks good. Even better than the original proposal in that you have longer hex strings where you need them (not separated byte-by-byte), makes these scripts very readable, I think.

**Comment by shargon** [comment]
I can update all of them. Wait for it

**Comment by shargon** [comment]
Take a look, because the conversion was made automatically, I needed to define a format for the enums. I choose uppercase for the `VM State` and Opcodes, and camelcase for the others.

**Comment by erikzhang** [comment]
For very large `ByteArray`, we can use placeholder instead. Example:

```json
{
  "script": [
    "PUSHDATA4",
    "0x00001000",
    {
      "type": "ByteArray",
      "element": 0,
      "repeat": 65536
    }
  ]
}
```

**Comment by shargon** [comment]
What do you think about detect the *. and do something like this
`0x00*2000`

**Comment by erikzhang** [comment]
Good idea.

**Comment by shargon** [comment]
Now it's possible to parse this kind of scripts

```
(0x01fF)*1024"
"0x0a0b0C*1024"
"0f*4096"
```

**Comment by erikzhang** [comment]
Go?

**Pull request merged**
