### PR TITLE
Remove SHA functions

### PR DESCRIPTION
**Pull request by igormcoelho**
Removing SHA functions and also removing the implicit name hashing on NeoVM.
This way, VM may simply pass interop calls to the Application layer to resolve them (by name or by hash). It could be possible to enforce 4 bytes on interop and fully remove names, but I think that explicit names can be useful on some platforms (without hashing). What do you think?

### CODE REVIEW

**Comment by erikzhang** [comment]
We are going to keep them.

**Comment by vncoelho** [comment]
Why,@erikzhang? Lets keep it all clear.

**Comment by erikzhang** [comment]
Because they are very common used instructions and do not depend on NEO.

**Comment by shargon** [comment]
I agree with @vncoelho , I think that is easier to keep the VM without crypto or hashing methods.

**Comment by shargon** [comment]
SHA is broken, i am agree with remove this opcode

**Comment by erikzhang** [comment]
Let's do it.

**Comment by shargon** [comment]
Conflicts and doesn't compile

**Pull request closed without merging**
