### PR TITLE
Add `PreExecuteInstruction()` and `PostExecuteInstruction()` virtual methods

### PR DESCRIPTION
**Pull request by erikzhang**
These methods are added for doing some additional verifications in sub class. Such as `gas` check.

### CODE REVIEW

**Comment by ixje** [comment]
Can you describe the purpose of these new methods? The only opcode that currently doesn't require a n `ExecutionContext` is `THROW` or is there a discussion for new ones somewhere?

**Comment by erikzhang** [comment]
You can get the current `ExecutionContext` via calling `ExecutionEngine.CurrentContext`.

**Comment by ixje** [comment]
The updated issue description clarifies.

**Comment by shargon** [comment]
Maybe we should return a `bool` if is valid or we need to throw and exception

**Comment by erikzhang** [comment]
Just throws exceptions if not valid.

**Pull request merged**
