### PR TITLE
Native contract

### PR DESCRIPTION
**Pull request by lightszero**
make script as a Interface，so nativeScript can based on this.

### CODE REVIEW

**Comment by shargon** [comment]
Is a good idea, but then `ExecuteOp` should be moved to `Script` class.

**Comment by erikzhang** [comment]
The design of Native Contract is not like this. Please see this issue: https://github.com/neo-project/neo/issues/303

**Comment by lightszero** [comment]
@erikzhang  sorry,i miss that. I agree most part of that issue. I will close this,and writecode in that way

**Comment by igormcoelho** [comment]
Man, I think Native Contracts should belong to NeoContract layer, so it's out of the scope for neo-vm :smile:

**Comment by lightszero** [comment]
discuss in #neo-project/neo#303

**Pull request closed without merging**
