### PR TITLE
Thread safe static items (v2)

### PR DESCRIPTION
**Pull request by shargon**
Fix https://github.com/neo-project/neo-vm/issues/477
Close https://github.com/neo-project/neo-vm/pull/479
According to https://github.com/neo-project/neo-vm/pull/478#issuecomment-1149883719

### CODE REVIEW

**Comment by devhawk** [comment]
I don't have permission to update this PR, but I tried this locally and it did the trick:

```cs
        [ThreadStatic]
        private static Boolean? tls_false = null;

        /// <summary>
        /// Represents <see langword="false"/> in the VM.
        /// </summary>
        public static Boolean False
        {
            get
            {
                tls_false ??= new(false);
                return tls_false;
            }
        }

        [ThreadStatic]
        private static Null? tls_null = null;

        /// <summary>
        /// Represents <see langword="null"/> in the VM.
        /// </summary>
        public static StackItem Null
        {
            get
            {
                tls_null ??= new();
                return tls_null;
            }
        }

        [ThreadStatic]
        private static Boolean? tls_true = null;

        /// <summary>
        /// Represents <see langword="true"/> in the VM.
        /// </summary>
        public static Boolean True 
        {
            get
            {
                tls_true ??= new(true);
                return tls_true;
            }
        }
```

**Comment by shargon** [comment]
@devhawk could you try with my last change?

**Comment by shargon** [comment]
Note that I reordered the fields, just for have the boolean together

**Comment by devhawk** [comment]
> @devhawk your changes was applied.

And thank you for reordering the fields from False/Null/True to True/False/Null. Semantics trumps alphabetical order in this case

**Review by devhawk — APPROVED** [review]
I like this change better than #478 due to known perf differences between Dictionary and ConcurrentDictionary. And it's better than #479 because it doesn't have any breaking changes.

**Comment by devhawk** [comment]
@superboyiii can you please run your test from #477 on this change?

**Review by devhawk — APPROVED** [review]

**Comment by superboyiii** [comment]
> @superboyiii can you please run your test from #477 on this change?

Sure.

**Review by erikzhang — APPROVED** [review]

**Comment by superboyiii** [comment]
It works well on my pressure test. 44608 txs and correct balance, no failed execution.
.

**Review by superboyiii — APPROVED** [review]

**Pull request merged**
