### PR TITLE
Remove `CHECKSIG`, `VERIFY`, and `CHECKMULTISIG`

### PR DESCRIPTION
**Pull request by erikzhang**
We should remove these opcodes, and add SYSCALLs in NEO as replacements.

### CODE REVIEW

**Comment by shargon** [comment]
Any idea about how to deal with the addresses?

**Comment by erikzhang** [comment]
> Any idea about how to deal with the addresses?

We can create a tool to help users create new standard addresses. Then use this tool to redeem new tokens when migrating to 3.0.

**Comment by vncoelho** [comment]
@igormcoelho

**Comment by igormcoelho** [comment]
Very good Erik, so vm will be nearly cryptography free? Are hashes going away too?

**Comment by erikzhang** [comment]
We are going to keep the hash functions.

**Comment by hal0x2328** [comment]
This is going to cause people to lose funds. People are going to inadvertently send Neo3 tokens to their Neo2 address, this is guaranteed. Then those funds can no longer be moved because the verification script doesn't match the owning scripthash. 

I don't think the benefit of conserving a few opcodes by converting these to interop methods is worth the headache it will cause; it could end up being a really bad situation for some people, one that is easily avoided by leaving the signature script backwards-compatible.

**Comment by shargon** [comment]
We want to change the version of the address

**Pull request merged**
