### PR TITLE
Fixes GetEntryScriptHash and GetCallingScriptHash (2.x)

### PR DESCRIPTION
**Pull request by erikzhang**
Port #134 to 2.x. Needs to check whether will it break old contracts.

### CODE REVIEW

**Comment by vncoelho** [comment]
Perfect, @erikzhang, thanks.
We are going to sync two different benchmark clients and check their storage.
What is the expected deadline? Maybe we gonna need some couple of days here, the stack is becoming big...

**Comment by erikzhang** [comment]
> What is the expected deadline?

As soon as possible please ....

**Comment by shargon** [comment]
I will approve it when i tested the storages, the code looks well

**Comment by erikzhang** [comment]
Can I merge it?

**Comment by shargon** [comment]
give me one day more

**Comment by shargon** [comment]
I need before #140 because i can't check the difference without it

**Comment by vncoelho** [comment]
```cs
SmartContract/StandardService.cs(135,63): error CS1061: 'ExecutionEngine' does not contain a definition for 'CallingContext' and no accessible extension method 'CallingContext' accepting a first argument of type 'ExecutionEngine' could be found (are you missing a using directive or an assembly reference?) [/opt/neoLib/neo/neo.csproj]
SmartContract/StandardService.cs(141,63): error CS1061: 'ExecutionEngine' does not contain a definition for 'EntryContext' and no accessible extension method 'EntryContext' accepting a first argument of type 'ExecutionEngine' could be found (are you missing a using directive or an assembly reference?) [/opt/neoLib/neo/neo.csproj]
```

**Comment by erikzhang** [comment]
Use `ExecutionEngine.CurrentContext.CallingScriptHash` and `ExecutionEngine.EntryScriptHash`.

**Comment by shargon** [comment]
Checking ....

**Comment by superboyiii** [comment]
Whole mainnet without issues.

**Pull request merged**
