### PR TITLE
README: add archival notice

### PR DESCRIPTION
**Pull request by roman-khimov**
People are likely to find this repo and we better have some directions for them.

### CODE REVIEW

**Comment by roman-khimov** [comment]
@dotnet-policy-service -EIDONTCARE

**Review by Liaojinghui — APPROVED** [review]

**Comment by Liaojinghui** [comment]
@shargon can add it to the description to this repo.

**Comment by roman-khimov** [comment]
GH adds a notice to archived repositories (https://github.com/nspcc-dev/ansible-neofs-rest-gw for example), the problem is that it doesn't explain _why_ it's archived and what to do with it. Therefore this PR.

**Comment by Liaojinghui** [comment]
@shargon merge?

**Review by shargon — APPROVED** [review]

**Pull request merged**
