### PR TITLE
Alow to convert Null to Boolean

### PR DESCRIPTION
**Pull request by shargon**
Close https://github.com/neo-project/neo-vm/issues/278

### CODE REVIEW

**Comment by erikzhang** [comment]
If `null` can be converted to `bool`, why it can't be converted to `0` or something else? I think we'd better keep it as `null`.

**Comment by shargon** [comment]
`If(null)` is a kind of conversion and it's treated as `false`

**Comment by superboyiii** [comment]
@erikzhang Shall we support this kind of source or must make a judgement before `add` if `toValue` is null?
image

**Comment by lightszero** [comment]
I do not think we need this.
compiler can add a isnull for it.
and unittest for it?

**Comment by shargon** [comment]
I will close it then

**Pull request closed without merging**
