### PR TITLE
add max_size

### PR DESCRIPTION
**Pull request by Liaojinghui**
following https://github.com/neo-project/neo/pull/2671 and https://github.com/neo-project/neo-modules/pull/696
we need to make the stack size consistent everywhere.

### CODE REVIEW

**Comment by shargon** [comment]
Currently is used https://github.com/neo-project/neo-vm/blob/b18e040d2115ed2ea3c9a60ae8722a7865b38927/src/neo-vm/ExecutionEngineLimits.cs#L34

**Comment by Liaojinghui** [comment]
Its different, that MAXSTACKSIZE is the maximum number of stackItem allowed in the stack at runtime. The MAX_SIZE here I defined is the size of the stack in bytes.

**Comment by shargon** [comment]
where is controlled? How it will deal with references?

**Comment by ixje** [comment]
Shouldn't we finalise the discussion of https://github.com/neo-project/neo-vm/issues/245 before implementing something? Even if it is not changing from reference counting, the discussion seems relevant.

**Comment by erikzhang** [comment]
I don't think it should be implemented in vm level.

**Comment by Liaojinghui** [comment]
> I don't think it should be implemented in vm level.

Only if we do not need the stack size to be  consistent, otherwise, we need to assign a max_byte_size to the stack when it is initialized. Because it is used cross multiple projects and different stack may need different size restriction:

resultstck for example:

https://github.com/neo-project/neo-express/blob/bbde1ff6b932277fb7ffd5313b12e784edb16d56/src/neoxp/Node/OfflineNode.cs#L127

https://github.com/neo-project/neo-node/blob/115e189008f112a001c651e6737e2241f35c5e0b/neo-gui/GUI/InvokeContractDialog.cs#L93

https://github.com/neo-project/neo-modules/blob/43298b065b2c42526f1c7f7bd691f4a79bc077c0/src/RpcServer/RpcServer.SmartContract.cs#L78
https://github.com/neo-project/neo-gui-2.x/blob/b816efbadc9bc731bf5ccd4cb545303bd39aabfa/neo-gui/UI/InvokeContractDialog.cs#L188

https://github.com/neo-project/neo-node/blob/24bd2ccfb7abd6ccdcb2e539a9896d1c3b02a4a7/neo-cli/CLI/MainService.cs#L655

https://github.com/neo-project/neo-modules/blob/e99d099fd3ae87e7cf6921f7f8e8f1d94f710dab/src/RpcServer/RpcServer.Wallet.cs#L382

https://github.com/neo-project/neo-debugger/blob/bc68ce1b61f5cbcd1ba60f51f1bccc133613f85e/src/adapter2/DebugSession.cs#L480

**Pull request closed without merging**
