### PR TITLE
Check items after copy an array/struct (2x)

### PR DESCRIPTION
**Pull request by shargon**
Require to test the backward compatibility (with mainnet and testnet)

### CODE REVIEW

**Comment by shargon** [comment]
@superboyiii Could you test it with the mainnet/testnet chain if this is backward compatible or not?

**Comment by shargon** [comment]
Ping @superboyiii

**Comment by lock9** [comment]
@shargon  how to properly test this? Syncing the whole network? 
@vncoelho  what is the name of that tool that you guys made (I think) to check 'storage' integrity?

**Comment by superboyiii** [comment]
@shargon Sorry for late, I'll test it.

**Comment by superboyiii** [comment]
@lock9 Hey Rick, you need to use StatesDumper Plugin to compare storage state.  Syncing the whole network, mainnet and testnet is necessary.

**Comment by lock9** [comment]
Thanks @superboyiii!

**Comment by meevee98** [comment]
@shargon I'm trying to test the changes in this pull request. Do you know in which situations the check should fail so I can replicate them?

**Comment by superboyiii** [comment]
@meevee98 If StatesDumper datas shows different result，I mean in the same block, the same operation causes different state changed, it should be fail.

**Comment by shargon** [comment]
The problem with these kind of changes is that it could happen in previous SmartContracts, so as @superboyiii said, we need to check the states with whole chain.

**Comment by superboyiii** [comment]
@shargon Due to my test on mainnet, it's compatible with previous version.
image
Only 4 places shows differences, but I find it's the defect of StatesDumper Plugin, these 4 places shows no incompatible state change but just serveral blocks' data missing on original version not yours. 
image
So, your fix is compatible. I'll catch up testnet comparison result tommorrow.

**Comment by shargon** [comment]
Thanks for the work!

**Comment by superboyiii** [comment]
@shargon Testnet comparison shows the same result.
image
Test pass.

**Comment by superboyiii** [comment]
@erikzhang

**Comment by erikzhang** [comment]
Did you test it with mainnet?

**Comment by superboyiii** [comment]
@erikzhang Yes, it was on my previous test 21 hour ago, 3 floors above.

**Comment by erikzhang** [comment]
But you said "Testnet comparison shows the same result."

**Comment by superboyiii** [comment]
@erikzhang I mean the same test result as what I got on mainnet.It's compatible with previous version. 
Only 2 places shows differences, but it's the defect of StatesDumper Plugin, these 2 places shows no incompatible state change but just serveral blocks' data missing.Just a little sync issue on StatesDumper.

**Comment by erikzhang** [comment]
So should I merge it?

**Comment by superboyiii** [comment]
Yes.

**Pull request merged**
